### ISSUE TITLE
 shutter switch not recognized in Domoticz

### ISSUE THREAD

**Issue by titis78** [Xenomes/Domoticz-TinyTUYA-Plugin#121]
Hello, I cannot get my device bff4cb11f4148ba722rgtk shutter switch to be recognized in Domoticz. It's a wifi shutter switch. the other device like T&H are OK. Here, I joined my dump file.
[dump.json](https://github.com/user-attachments/files/16922955/dump.json)

**Comment by Xenomes** [comment]
The shutter recently had an overlap with the switch category, so I’ve added this product ID to the cover category. See version 1.9.8

**Comment by titis78** [comment]
Thank you, that's work fine.

**Comment by Xenomes** [comment]
Perfect!

**Comment by Epik77** [comment]
sorry but not works  :-(


2024-09-16 07:09:52.274 Error: SmartLife Cloud: Call to function 'onCommand' failed, exception details:
2024-09-16 07:09:52.276 Error: SmartLife Cloud: Traceback (most recent call last):
2024-09-16 07:09:52.276 Error: SmartLife Cloud: File "/opt/domoticz/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 775, in onCommand
2024-09-16 07:09:52.276 Error: SmartLife Cloud: _plugin.onCommand(DeviceID, Unit, Command, Level, Color)
2024-09-16 07:09:52.276 Error: SmartLife Cloud: File "/opt/domoticz/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 139, in onCommand
2024-09-16 07:09:52.276 Error: SmartLife Cloud: function = properties[DeviceID]['functions']
2024-09-16 07:09:52.276 Error: SmartLife Cloud: KeyError: 'bfb1e9991554ad9131qsah' 


 2024-09-16 07:10:12.102 Error: SmartLife Cloud: handleThread: string indices must be integers line 882
2024-09-16 07:10:22.085 Error: SmartLife Cloud: handleThread: string indices must be integers line 882

**Comment by Epik77** [comment]
sorry the problem is:
2024-09-16 14:54:05.661 SmartLife Cloud: No device data returned for Tuya! Check if subscription cloud plan has expired!
I just renewed, I hope they unblock me soon

**Comment by Xenomes** [comment]
Okay, let me know, i have create a fix for the error 'integers line 882'
