### ISSUE TITLE
No Devices created in Domoticz for Adlar Aurora II heat pump

### ISSUE THREAD

**Issue by nlfva1** [Xenomes/Domoticz-TinyTUYA-Plugin#131]
I have Domoticz 2024.7 and Python 3.8.1 and installed the TinyTUYA plugin 2.0.4. I did all the steps in Tuya developer platform and can receive the data in my raspberry using "python -m tinytuya scan" see below, but it does not create the devices in Domoticz when activating the plugin.

![image](https://github.com/user-attachments/assets/225abfe7-557e-4349-b538-41fa7e3d3ba9)

In the domoticz log  I get two messages: 
- Crypto library does not support GCM line 925
- Device not found in Domoticz! Has the device been removed

Let me know if you need more info.

**Comment by Xenomes** [comment]
Hi, that is the same issue as #126. I don’t have a clue yet what is causing the error. What OS are you running on the RPI?

**Comment by nlfva1** [comment]
I'm running Raspbian GNU/Linux 10 (buster) Linux 5.10.103-v7l+

I've added dump.json as I guess that this wil be your next question😉
[dump.json](https://github.com/user-attachments/files/17466682/dump.json)

**Comment by nlfva1** [comment]
I added the path of the tinytuya module to your script and found that it's actually still pointing to version 3.7, so looks like it's related to the python version. Although I have installed python 3.8.1.

![Screenshot 2024-10-26 142544](https://github.com/user-attachments/assets/314cf88d-6a3b-487e-9774-8285d081ce4b)

Now trying to figure out how to fix this. so far not successful. Will try to update to python 3.8.5 instead.

**Comment by Xenomes** [comment]
Normally you can set the default python by running:
`update-alternatives --config python`

**Comment by nlfva1** [comment]
Unfortunately the command did not help.  

Domoticz is still loading 3.7.3 and not libpython3.8.5. Looks like something with the pythonpath in Domoticz. I'll keep looking, but open for suggestions..

Error: Tuya cloud: (tinytuya) failed to load 'plugin.py', **Python Path** used was '/home/pi/domoticz/plugins/Domoticz-TinyTUYA-Plugin/:/usr/lib/python37.zip:/usr/lib/python3.7:/usr/lib/python3.7/lib-dynload:/usr/local/lib/python3.7/

Even tried installing 3.9.7, but did not help either.  Still pointing to 3.7.

**Comment by Xenomes** [comment]
Did you try running it with sudo? Domoticz runs under the su (superuser) account.

**Comment by nlfva1** [comment]
Yes.  Here is the result:
_sudo  update-alternatives --config python_
There is only one alternative in link group python (providing /usr/bin/python): /usr/local/bin/python3.8
**Nothing to configure.**

Still showing python version  3.7.3 in Domoticz.  Also tried it with an empty new domoticz database, but same result.  I have no clue where it getting the 3.7.3 from.

**Comment by Xenomes** [comment]
That is strange, python3 -V give 3.8?

**Comment by nlfva1** [comment]
Yes.  I will try a deinstall and reinstall of domoticz to see if that works.  
![Screenshot_20241102_100022_Putty SSH](https://github.com/user-attachments/assets/ac5b044c-216f-4857-876a-89f189fd7ce2)

**Comment by Xenomes** [comment]
And sudo python3 -V
How did you insta?ll python 3.8?

**Comment by nlfva1** [comment]
Same result.  Let me try the reinstall of domoticz first. Thanks so far.

**Comment by Xenomes** [comment]
Was the reinstall the fix?

**Comment by nlfva1** [comment]
No the re-install with a fresh domoticz.db still gave the same 3.7.3 versionin the domoticz log. Although sudo python --version and sudo python3 -- version both give version 3.8.1. Even tried a PYTHONPATH in domoticz.sh and point to 3.8.1, but is not picking up. Copied my backed up domoticz.db back to this new installation and after start up still pointing to 3.7.3.

![image](https://github.com/user-attachments/assets/c047ae96-2180-42d4-a3a1-f522078b8cdc)

I'm out of option other then a complete reinstall of raspbian and domoticz, but is not something I'm looking forward to.  Will first by a new 32gb memory card, so that it's easier to go back if it isn't working. To be continued, but open for other idea's. Thanks so far.

**Comment by Xenomes** [comment]
There was a self closed ticked, of someone had a issue what give me a idea.
What is the version of in python 3.7.3? 
`sudo python3.7 -m pip show cryptography`
if this is higher then 3.4.8, downgrade to 3.4.8
`sudo python3.7 -m pip install cryptography==3.4.8`

**Comment by nlfva1** [comment]
Thanks.  Tried it. Het is the result.  Version is 2.6, so even lower than 3.4.8.

![Screenshot_20241104_222236_Putty SSH](https://github.com/user-attachments/assets/3e5c858b-ee0a-413c-bce9-95db0365e3b6)

Should I update it to 3.4.8?

**Comment by Xenomes** [comment]
Can you try `sudo python3.7 -m pip install cryptography==` then it will show all versions.

**Comment by nlfva1** [comment]
A lot of errors...

pi@homepi:~ $  sudo python3.7 -m pip install _cryptography==
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/bas
e_command.py", line 143, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/command
s/install.py", line 279, in run
    with self._build_session(options) as session:
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/bas
e_command.py", line 79, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/usr/lib/python3/dist-packages/pip/_internal/downloa
d.py", line 337, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/lib/python3/dist-packages/pip/_internal/downloa
d.py", line 100, in user_agent
    zip(["name", "version", "id"], distro.linux_distribution
()),
  File "/usr/share/python-wheels/distro-1.3.0-py2.py3-none-a
ny.whl/distro.py", line 120, in linux_distribution
    return _distro.linux_distribution(full_distribution_name
)
  File "/usr/share/python-wheels/distro-1.3.0-py2.py3-none-a
ny.whl/distro.py", line 675, in linux_distribution
    self.version(),
  File "/usr/share/python-wheels/distro-1.3.0-py2.py3-none-a
ny.whl/distro.py", line 735, in version
    self.lsb_release_attr('release'),
  File "/usr/share/python-wheels/distro-1.3.0-py2.py3-none-a
ny.whl/distro.py", line 892, in lsb_release_attr
    return self._lsb_release_info.get(attribute, '')
  File "/usr/share/python-wheels/distro-1.3.0-py2.py3-none-a
ny.whl/distro.py", line 550, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/usr/share/python-wheels/distro-1.3.0-py2.py3-none-a
ny.whl/distro.py", line 998, in _lsb_release_info
    stdout = subprocess.check_output(cmd, stderr=devnull)
  File "/usr/lib/python3.7/subprocess.py", line 395, in chec
k_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('lsb_release', '-a'
)' returned non-zero exit status 1._
pi@homepi:~ $ 

Hope this info helps you in  one way or the other.

**Comment by Xenomes** [comment]
I see there is a underscore in your command.

**Comment by nlfva1** [comment]
Weird. Don't know how that happened. Tried it without the _, but still a lot of errors. 

![Screenshot_20241105_230729_Putty SSH](https://github.com/user-attachments/assets/84926406-8e67-42af-bdcc-461dbf6c64d3)

I will order a new sd card and will try a fresh installation, but will take a while to complete. No worries.

**Comment by Xenomes** [comment]
Okay, need help let me know!

**Comment by nlfva1** [comment]
Just received the new sd card and starting with the installation. I saw in the other conversion that you mentioned to install bullseye  instead of bookworm. Is there a specific reason to go for Bullseye?

**Comment by Xenomes** [comment]
In a older version of Domoticz there was a issue running it on the latest release of Raspberry OS. At the moment there are no unknown issues.
https://www.domoticz.com/wiki/Raspberry_Pi

**Comment by nlfva1** [comment]
Domoticz is working and python is 3.11, but I it did not allow me to install tinytuya, so I had to install it with an override using:
_python -m pip install tinytuya --break-system-packages_

After this I installed the Domoticz-TinyTUYA-Plugin, but when I tried to start it, it could not import tinytuya. Found that the path in the plugin was different from I temporarily added _sys.path.append('/home/pi/.local/lib/python3.11/site-packages')_.

After the restart of Domoticz it's working like a charm. It also created the devices for Adlar Aurora II heat pump, but I must admit that compared to HA there are a lot of devices not created. 

![Screenshot 2024-11-08 221036](https://github.com/user-attachments/assets/bd3b1d98-967e-4b8f-b79c-8e2e17ded12e)

![Screenshot 2024-11-08 215552](https://github.com/user-attachments/assets/3499eab3-1d99-44ab-9540-db488e923866)

In HA I also see devices like power consumption, power consumption today, heat-curve-set etc, although I do see them in the domoticz log. See below.  Is this as expected or should these be created as well ?
![Screenshot 2024-11-08 220031](https://github.com/user-attachments/assets/bbe72ec8-432d-4a35-a3db-dd1d8d6ecd81)

**Comment by Xenomes** [comment]
There are many devices with different configurations, making it impractical to add them all upfront. If you need specific devices, feel free to clone the plugin, add them, test, and then submit a pull request to update the plugin for everyone.

**Comment by Xenomes** [comment]
> Domoticz is working and python is 3.11, but I it did not allow me to install tinytuya, so I had to install it with an override using: _python -m pip install tinytuya --break-system-packages_
> 
> After this I installed the Domoticz-TinyTUYA-Plugin, but when I tried to start it, it could not import tinytuya. Found that the path in the plugin was different from I temporarily added _sys.path.append('/home/pi/.local/lib/python3.11/site-packages')_.
> 
> After the restart of Domoticz it's working like a charm. It also created the devices for Adlar Aurora II heat pump, but I must admit that compared to HA there are a lot of devices not created.

Very good! In newer versions of Python 3, an override is required, as Domoticz does not have a private Python environment. Normally, running sudo pip3 install places the modules in the correct location.
