### ISSUE TITLE
NameError: name 'last_update' is not defined

### ISSUE THREAD

**Issue by lamama1234** [Xenomes/Domoticz-TinyTUYA-Plugin#30]
I just installed yesterday and getting the following log error:

```
2023-03-07 14:59:59.074 Error: TinyTUYA: Call to function 'onHeartbeat' failed, exception details:
2023-03-07 14:59:59.075 Error: TinyTUYA: Traceback (most recent call last):
2023-03-07 14:59:59.075 Error: TinyTUYA: File "C:\Program Files (x86)\Domoticz\plugins\Domoticz-TinyTUYA-Plugin-Master\plugin.py", line 341, in onHeartbeat
2023-03-07 14:59:59.075 Error: TinyTUYA: _plugin.onHeartbeat()
2023-03-07 14:59:59.076 Error: TinyTUYA: File "C:\Program Files (x86)\Domoticz\plugins\Domoticz-TinyTUYA-Plugin-Master\plugin.py", line 302, in onHeartbeat
2023-03-07 14:59:59.076 Error: TinyTUYA: if time.time() - last_update < 60 and testData == False:
2023-03-07 14:59:59.076 Error: TinyTUYA: NameError: name 'last_update' is not defined
```

No Tuya devices added obviously.

Running SmartLife (only one device paired: smart water valve), Domoticz 2023.1 on Win7 w/ Python 3.8.

IOT API subscription is still valid.

Thanks

**Comment by Xenomes** [comment]
Hi, I think the device is not found and the stop at a point the last_update is not created. I will check the code.
Edit: I was correct, please pull the plugin again, a little modification will make the script run.
