### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer | Call to function 'onCommand' failed

### ISSUE THREAD

**Issue by bwbboot** [Xenomes/Domoticz-TinyTUYA-Plugin#81]
Both in Master as in Develop I get the following error messages.  I have changed debug level to all to record more details.
Domoticz 2024.1 RPI 5

Any idea what is causing this?

2024-01-06 22:25:03.368 Error: TinyTUYA: Call to function 'onCommand' failed, exception details:
2024-01-06 22:25:03.370 Error: TinyTUYA: Traceback (most recent call last):
2024-01-06 22:25:03.370 Error: TinyTUYA: File "/home/pi/domoticz/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 624, in onCommand
2024-01-06 22:25:03.370 Error: TinyTUYA: _plugin.onCommand(DeviceID, Unit, Command, Level, Color)
2024-01-06 22:25:03.370 Error: TinyTUYA: File "/home/pi/domoticz/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 312, in onCommand
2024-01-06 22:25:03.370 Error: TinyTUYA: UpdateDevice(DeviceID, 3, Level, 1, 0)
2024-01-06 22:25:03.370 Error: TinyTUYA: File "/home/pi/domoticz/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 2927, in UpdateDevice
2024-01-06 22:25:03.370 Error: TinyTUYA: Devices[ID].Units[Unit].LastLevel = sValue
2024-01-06 22:25:03.370 Error: TinyTUYA: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-06 22:25:03.370 Error: TinyTUYA: TypeError: 'float' object cannot be interpreted as an integer
2024-01-06 22:25:03.499 Error: TinyTUYA: Call to function 'onCommand' failed, exception details:
2024-01-06 22:25:03.500 Error: TinyTUYA: Traceback (most recent call last):
2024-01-06 22:25:03.500 Error: TinyTUYA: File "/home/pi/domoticz/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 624, in onCommand
2024-01-06 22:25:03.500 Error: TinyTUYA: _plugin.onCommand(DeviceID, Unit, Command, Level, Color)
2024-01-06 22:25:03.500 Error: TinyTUYA: File "/home/pi/domoticz/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 312, in onCommand
2024-01-06 22:25:03.500 Error: TinyTUYA: UpdateDevice(DeviceID, 3, Level, 1, 0)
2024-01-06 22:25:03.500 Error: TinyTUYA: File "/home/pi/domoticz/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 2927, in UpdateDevice
2024-01-06 22:25:03.500 Error: TinyTUYA: Devices[ID].Units[Unit].LastLevel = sValue
2024-01-06 22:25:03.500 Error: TinyTUYA: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-06 22:25:03.500 Error: TinyTUYA: TypeError: 'float' object cannot be interpreted as an integer
2024-01-06 22:25:03.684 Error: TinyTUYA: Call to function 'onCommand' failed, exception details:
2024-01-06 22:25:03.685 Error: TinyTUYA: Traceback (most recent call last):
2024-01-06 22:25:03.685 Error: TinyTUYA: File "/home/pi/domoticz/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 624, in onCommand
2024-01-06 22:25:03.685 Error: TinyTUYA: _plugin.onCommand(DeviceID, Unit, Command, Level, Color)
2024-01-06 22:25:03.685 Error: TinyTUYA: File "/home/pi/domoticz/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 312, in onCommand
2024-01-06 22:25:03.685 Error: TinyTUYA: UpdateDevice(DeviceID, 3, Level, 1, 0)
2024-01-06 22:25:03.685 Error: TinyTUYA: File "/home/pi/domoticz/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 2927, in UpdateDevice
2024-01-06 22:25:03.685 Error: TinyTUYA: Devices[ID].Units[Unit].LastLevel = sValue
2024-01-06 22:25:03.685 Error: TinyTUYA: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-06 22:25:03.685 Error: TinyTUYA: TypeError: 'float' object cannot be interpreted as an integer
2024-01-06 22:25:03.817 Error: TinyTUYA: Call to function 'onCommand' failed, exception details:
2024-01-06 22:25:03.818 Error: TinyTUYA: Traceback (most recent call last):
2024-01-06 22:25:03.818 Error: TinyTUYA: File "/home/pi/domoticz/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 624, in onCommand
2024-01-06 22:25:03.818 Error: TinyTUYA: _plugin.onCommand(DeviceID, Unit, Command, Level, Color)
2024-01-06 22:25:03.818 Error: TinyTUYA: File "/home/pi/domoticz/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 312, in onCommand
2024-01-06 22:25:03.818 Error: TinyTUYA: UpdateDevice(DeviceID, 3, Level, 1, 0)
2024-01-06 22:25:03.818 Error: TinyTUYA: File "/home/pi/domoticz/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 2927, in UpdateDevice
2024-01-06 22:25:03.818 Error: TinyTUYA: Devices[ID].Units[Unit].LastLevel = sValue
2024-01-06 22:25:03.818 Error: TinyTUYA: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-06 22:25:03.818 Error: TinyTUYA: TypeError: 'float' object cannot be interpreted as an integer
2024-01-06 22:25:03.820 Error: TinyTUYA: Call to function 'onCommand' failed, exception details:
2024-01-06 22:25:03.821 Error: TinyTUYA: Traceback (most recent call last):
2024-01-06 22:25:03.821 Error: TinyTUYA: File "/home/pi/domoticz/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 624, in onCommand
2024-01-06 22:25:03.821 Error: TinyTUYA: _plugin.onCommand(DeviceID, Unit, Command, Level, Color)
2024-01-06 22:25:03.821 Error: TinyTUYA: File "/home/pi/domoticz/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 311, in onCommand
2024-01-06 22:25:03.821 Error: TinyTUYA: SendCommandCloud(DeviceID, switch3, Level)
2024-01-06 22:25:03.821 Error: TinyTUYA: File "/home/pi/domoticz/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 2967, in SendCommandCloud
2024-01-06 22:25:03.821 Error: TinyTUYA: actual_status = set_scale(sendfunction, actual_function_name, Status)
2024-01-06 22:25:03.821 Error: TinyTUYA: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-06 22:25:03.821 Error: TinyTUYA: File "/home/pi/domoticz/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 3032, in set_scale
2024-01-06 22:25:03.821 Error: TinyTUYA: if result > max:
2024-01-06 22:25:03.821 Error: TinyTUYA: ^^^^^^^^^^^^
2024-01-06 22:25:03.821 Error: TinyTUYA: TypeError: '>' not supported between instances of 'int' and 'str'

**Comment by bwbboot** [comment]
Ok, I might have figured this out. 

I used to have my own script updating Tuya as Virtual Sensors in Domoticz. 
Since I am migrating from a RPI3 to 5, I had both systems running while also transitioning to this plugin on the new system.
The old system still had the script running and the IP was hardcoded causing it to update this plugins sensors using the Domoticz API in the new system.

I guess what happens, my script pulls sensor data from Tuya API, it then updates Domoticz sensors under control of this plugin. Which is causing TinyTUYA to update the sensor via Tuya API.  Should not be an issue, right?

However , since I also pull temperature data, which can't be updated in Tuya Cloud, I guess this is causing these error messages. 

I have removed the hardcoded IP from my old script, now monitoring to see if this resolved the issue.

**Comment by Xenomes** [comment]
Hi, I was just reading your first post. The error is in the update function of a thermostat. i am not 100% sure what is happening, I need to see the log commands before the error so we can see what is send. Maybe a wrong value is send to the thermostat.
> However , since I also pull temperature data, which can't be updated in Tuya Cloud, I guess this is causing these error messages.

the error is on the onCommand of Domoticz. so there is a change on a control device,

**Comment by bwbboot** [comment]
Ok I am closing this issue, it's fully related to my own script.

**Comment by Xenomes** [comment]
Okay, thanks for the feedback!
