### ISSUE TITLE
Error every minute

### ISSUE THREAD

**Issue by vespino** [Xenomes/Domoticz-TinyTUYA-Plugin#88]
I’m getting the following  error every minute:

`2024-02-02 20:40:23.163 Error: TinyTUYA: handleThread: Credentials are incorrect or tuya subscription has expired! line 748`

Every device is working fine though, but it’s flooding my logs.

**Comment by Xenomes** [comment]
On witch version are you?

**Comment by vespino** [comment]
The latest. And I now notice a lot of other stuff going wrong. Did my contribution break the plugin?

```
2024-02-02 22:40:11.201 Error: TinyTUYA: File "/opt/domoticz/userdata/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 633, in onCommand
2024-02-02 22:40:11.201 Error: TinyTUYA: _plugin.onCommand(DeviceID, Unit, Command, Level, Color)
2024-02-02 22:40:11.201 Error: TinyTUYA: File "/opt/domoticz/userdata/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 136, in onCommand
2024-02-02 22:40:11.201 Error: TinyTUYA: function = properties[DeviceID]['functions']
```

**Comment by Xenomes** [comment]
Strange... no the change is not casing this error it was in on_command. Can you check if debug_discovery give the correct output. I am running the plugin live no error with my device.

**Comment by vespino** [comment]
When turning on all debug info and restarting, I’m getting the following error every minute:

`2024-02-02 23:02:08.631 Error: TinyTUYA: handleThread: string indices must be integers line 718`

and the following info:

```
2024-02-02 23:03:58.036 TinyTUYA: Pushing 'onHeartbeatCallback' on to queue
2024-02-02 23:03:58.086 TinyTUYA: Processing 'onHeartbeatCallback' message
2024-02-02 23:03:58.086 TinyTUYA: Acquiring GIL for 'onHeartbeatCallback'
2024-02-02 23:03:58.086 TinyTUYA: Calling message handler 'onHeartbeat' on 'module' type object.
2024-02-02 23:03:58.086 TinyTUYA: onHeartbeat called
2024-02-02 23:03:58.086 TinyTUYA: onHeartbeat called last run: 109.64079236984253
2024-02-02 23:03:58.086 TinyTUYA: Acquiring GIL for 'onHeartbeatCallback'
```

Toggling a device gives the following error:

```
2024-02-02 23:05:14.981 Error: TinyTUYA: Call to function 'onCommand' failed, exception details:
2024-02-02 23:05:14.983 Error: TinyTUYA: Traceback (most recent call last):
2024-02-02 23:05:14.983 Error: TinyTUYA: File "/opt/domoticz/userdata/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 633, in onCommand
2024-02-02 23:05:14.983 Error: TinyTUYA: _plugin.onCommand(DeviceID, Unit, Command, Level, Color)
2024-02-02 23:05:14.983 Error: TinyTUYA: File "/opt/domoticz/userdata/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 136, in onCommand
2024-02-02 23:05:14.983 Error: TinyTUYA: function = properties[DeviceID]['functions']
```

What more info can I provide? Not sure why it stopped working, I apparently was running the version I modified before submitting my changes. I have now forced an update from GitHub, so I’m on the latest version from there.

**Comment by Xenomes** [comment]
I looks like there is a problem to connect to tuya server. Try the debug in the tools directory then we know for sure.

**Comment by vespino** [comment]
Can you tell me how to run it? I don’t know Python unfortunately.

**Comment by Xenomes** [comment]
Edit the file and fill in the same info as in the plugin. Run it with python.
`nano debug_discovery.py
python3 ./debug_discovery.py`

**Comment by Xenomes** [comment]
Edit the file and fill in the same info as in the plugin. Run it with python.
`nano debug_discovery.py
python3 ./debug_discovery.py`

**Comment by vespino** [comment]
I’ll give that a try tomorrow.

**Comment by vespino** [comment]
Oh nooo! "No permissions. Your subscription to cloud development plan has expired."

But why? Isn't this free for home use?

**Comment by Xenomes** [comment]
Yes it is, you can extent the subscription, see the link in the readme. 
![image](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/11648297/f7d615d0-1f21-437a-b108-1a3e7e925a05)

**Comment by vespino** [comment]
I found that, but do I have to renew that every 6 months? Or is it done after 6 months? For now I have reverted to https://github.com/Xenomes/Domoticz-TUYA-Plugin since the Mrs doesn't like it when she's kept in the dark (literally :)).

**Comment by Xenomes** [comment]
The strange thing is, some have to do a 6 months renew and some don't. Even the Home Assistant users have to renew and Tuya help develop the plugin there. maybe someone at Tuya who process the requests choose a other option.

> since the Mrs doesn't like it when she's kept in the dark (literally :))

I always try to make a bypass possible, it always happens when i am not at home. 😆

**Comment by vespino** [comment]
I know, right?! And the Mrs doesn't have the Tuya app.

**Comment by Xenomes** [comment]
You could try then https://github.com/Xenomes/Domoticz-TinyTUYA-Local-Plugin this is on/off only.

**Comment by vespino** [comment]
But what about this? https://github.com/Xenomes/Domoticz-TinyTUYA-Local-Plugin?tab=readme-ov-file#subscription-expired

**Comment by Xenomes** [comment]
The plugin runs on the data that is pulled once of the tuya server and stored as a json file. That is the only way to receive the device key.

**Comment by vespino** [comment]
I will wait for Tuya to extend my account first and take things from there. Funny thing is that their login shows my account already expired almost 2 years ago.

**Comment by Xenomes** [comment]
That is indeed strange... are you 100% you used the correct credentials?

**Comment by vespino** [comment]
Yes, it worked before yesterday and the only thing I changed was the logging level since I didn’t need all of it. I will try again since the plugin works great, even better than the old one since the doesn’t support RGBWW correctly (at least that’s what homebridge is saying).

**Comment by Xenomes** [comment]
Then the wait is on tuya to extent.

**Comment by vespino** [comment]
They have extended my account and I'm able to work via the cloud once again. Just to be sure, I set myself a reminder for over 6 months...

**Comment by Xenomes** [comment]
Very good!
